version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  southindiantrekkers:
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.backend=southindiantrekkers
      - traefik.frontend.rule=Host:southindiantrekkers.vaayadi.in
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy